-- public.buku definition

-- Drop table

-- DROP TABLE public.buku;

CREATE TABLE public.buku (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	isbn varchar(255) NULL,
	judul varchar(255) NULL,
	stok int4 NOT NULL,
	CONSTRAINT buku_pkey PRIMARY KEY (id),
	CONSTRAINT uk68gkum0wo4wjev89c9njawufu UNIQUE (isbn)
);