-- public.transaksi_peminjaman definition

-- Drop table

-- DROP TABLE public.transaksi_peminjaman;

CREATE TABLE public.transaksi_peminjaman (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	returned bool NOT NULL,
	tanggal_deadline date NULL,
	tanggal_pengembalian date NULL,
	tanggal_pinjam date NULL,
	buku_id int8 NULL,
	peminjam_no_ktp varchar(255) NULL,
	CONSTRAINT transaksi_peminjaman_pkey PRIMARY KEY (id)
);


-- public.transaksi_peminjaman foreign keys

ALTER TABLE public.transaksi_peminjaman ADD CONSTRAINT fkc2mc0m07ugaidium6h5ge77b2 FOREIGN KEY (buku_id) REFERENCES public.buku(id);
ALTER TABLE public.transaksi_peminjaman ADD CONSTRAINT fkk40c80i8894ilw0bkkceupqyb FOREIGN KEY (peminjam_no_ktp) REFERENCES public.peminjam(no_ktp);